apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kubernotify
  name: kubernotify
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kubernotify
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/streeteats-default: "true"
        io.kompose.service: kubernotify
    spec:
      containers:
        - image: kubernotify
          name: kubernotify
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6000
              # hostPort: 6000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
